{% set version = "0.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-runonce
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/runonce_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/runonce/runonce_{{ version }}.tar.gz
  sha256: 75ba9310074e4c9c16fdd4289743fd90008c5e38c037131d33bba045410dc5c5

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bigassertr
    - r-urltools
  run:
    - r-base
    - r-bigassertr
    - r-urltools

test:
  commands:
    - $R -e "library('runonce')"           # [not win]
    - "\"%R%\" -e \"library('runonce')\""  # [win]

about:
  home: https://github.com/privefl/runonce
  license: GPL-3.0-only
  summary: Package 'runonce' helps automating the saving of long-running code to help running the same code multiple times. If you run some long-running code once, it saves the result in a file on disk. Then, if the result already exists, i.e. if the code has already been run and its output has already been saved, it just
    reads the result from the stored file instead of running the code again.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - pettyalex

# Package: runonce
# Title: Run Once and Save Result
# Version: 0.2.3
# Authors@R: person("Florian", "Prive", role = c("aut", "cre"), email = "florian.prive.21@gmail.com")
# Description: Package 'runonce' helps automating the saving of long-running code to help running the same code multiple times. If you run some long-running code once, it saves the result in a file on disk. Then, if the result already exists, i.e. if the code has already been run and its output has already been saved, it just reads the result from the stored file instead of running the code again.
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Imports: bigassertr, urltools
# Suggests: testthat (>= 2.1.0), covr
# URL: https://github.com/privefl/runonce
# BugReports: https://github.com/privefl/runonce/issues
# NeedsCompilation: no
# Packaged: 2021-10-02 08:22:15 UTC; au639593
# Author: Florian Prive [aut, cre]
# Maintainer: Florian Prive <florian.prive.21@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-10-02 08:30:02 UTC
